version: '3.8'

services:
  db:
    image: postgres:16.1
    container_name: db-companies
    restart: always
    volumes:
      # Archivos SQL para inicialización de la base de datos
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
      # Volumen para persistencia de datos en una carpeta local
      - D:/DockerCourse/docker-compose-course/microservices/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'companies'
      POSTGRES_USER: 'developer'
      POSTGRES_PASSWORD: 'dev'
    ports:
      - '5432:5432'